#!/usr/bin/env python3

import pyASC
import sys

usage = "usage: $ testArchive <dirName> <dbName>"

if __name__ == "__main__":

    if len(sys.argv) < 3:
        print(usage)
        sys.exit()

    a = pyASC.archive.Archive(sys.argv[1], sys.argv[2])
    print(a)

    # print(a.nodes)
    # print(a.years)

    # for fit in a.getFITS('MASN-01', '20150918'):
    #     print(fit)
