#!/usr/bin/env python

import pyASC
import sys

usage = "usage: $ testArchive <dirName>"

if __name__ == "__main__":

    if len(sys.argv) < 2:
        print(usage)
        sys.exit()

    a = pyASC.archive.Archive(sys.argv[1])
    print(a)
    print(a.nodes)
    print(a.years)

    # for fit in a.getFITS('MASN-01', '20150918'):
    #     print(fit)
