<div class="container-fluid transparent-black-bg text-light">
	<footer class="footer">
		<div class="container-fluid text-center">
			<p>
				<a href="https://www.astro.umd.edu/openhouse/">
					Astronomy Observatory
				</a> |

				<a href="https://www.astro.umd.edu/">
					Dept. of Astronomy
				</a> |
				
				<a href="https://www.cmns.umd.edu/">
					CMNS
				</a> | 
				
				<a href="https://www.umd.edu">
					UMD
				</a>
				
				
				<br />

				<em><strong><a href="https://umd.edu/web-accessibility" target="_blank">Web Accessibility</a></strong></em>

				<br />

				Copyright &copy; 2019. All rights reserved.

				<br />

				Updated: <!--#config timefmt="%d-%h-%Y" --><!--#echo var="LAST_MODIFIED" -->
			</p>
		</div>
	</footer>
</div>