<!--Top bar-->
<div class="container-fluid transparent-black-bg text-light">

	<!--MASN Title banner-->
	<a class="text-light text-decoration-none" href="/index.shtml">
		<h2 class="text-center py-3">
			MARYLAND ALL-SKY NETWORK
		</h2>
	</a>

	<!--Navbar-->
	<nav class="navbar navbar-expand-md navbar-dark">
		<div class="">
			<a class="navbar-brand text-light" href="/index.shtml">
				MASN Home
			</a>
		</div>
  		
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
 		</button>

	  	<div class="collapse navbar-collapse" id="navbarTogglerDemo01">
	    	<ul class="navbar-nav">
		      	<li class="nav-item dropdown">
			        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			        	Cameras
			        </a>
			        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
			          	<a class="dropdown-item" href="/cameras/MASN-1.shtml">MASN&nbsp;01</a>
			          	<a class="dropdown-item" href="#">MASN&nbsp;02</a>
			          	<a class="dropdown-item" href="#">MASN&nbsp;03</a>
			          	<a class="dropdown-item" href="#">MASN&nbsp;04</a>
			          	<a class="dropdown-item" href="#">MASN&nbsp;05</a>
			        </div>
			    </li>

		      	<li class="nav-item dropdown">
			        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			          Archives
			        </a>
			        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
			          	<a class="dropdown-item" href="/archives/video.shtml">Videos</a>
			          	<a class="dropdown-item" href="/archives/meteor.shtml">Meteors</a>
			          	<a class="dropdown-item" href="/archives/other.shtml">Others</a>
			        </div>
			    </li>
		      	<li class="nav-item">
		        	<a class="nav-link" href="/technical.shtml">Technical</a>
		      	</li>
		     	<li class="nav-item">
		        	<a class="nav-link" href="/project.shtml">Project</a>
		      	</li>
    			<li class="nav-item">
		        	<a class="nav-link" href="#">Misc.</a>
		      	</li>
	    	</ul>
	<!--possible search bar
	    <form class="form-inline my-2 my-lg-0">
	      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
	      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
	    </form>
	-->
	  	</div>
	</nav>
	<!--Closes navbar-->
</div>
<!--Closes the top div-->